services:
  higlass:
    image: "higlass/higlass-docker"
    ports:
      - "${REACT_APP_HIGLASS_SERVER_PORT_HOST}:${REACT_APP_HIGLASS_SERVER_PORT_CONTAINER}"
    volumes:
      - db-data-higlass-data:/data
      - db-data-higlass-tmp:/tmp
    networks:
      - backend
    container_name: "higlass${REACT_APP_TEST}"
    env_file:
      - "${PWD}/.env"
  web_api:
    build: 
      context: .
      dockerfile: dockerfile.server  # Specify the name of the Dockerfile
    ports:
      - "${REACT_APP_WEB_API_PORT_HOST}:${REACT_APP_WEB_API_PORT_CONTAINER}" #8086 is the internal port hosted on inside the docker
    depends_on:
      - higlass
    volumes:
      - ${PWD}:${REACT_APP_CONTAINER_MOUNT_POINT}
    networks:
      - backend
    container_name: "web_api${REACT_APP_TEST}"
    env_file:
      - "${PWD}/.env"
  flask_api:
    build: 
      context: .
      dockerfile: dockerfile.server  # Specify the name of the Dockerfile
    ports:
      - "${REACT_APP_FLASK_API_PORT_HOST}:${REACT_APP_FLASK_API_PORT_CONTAINER}" #8087 is the internal port hosted on inside the docker
    depends_on:
      - higlass
    volumes:
      - ${PWD}:${REACT_APP_CONTAINER_MOUNT_POINT}
    networks:
      - backend
    command: npm run start-flask-api
    container_name: "flask_api${REACT_APP_TEST}"
    env_file:
      - "${PWD}/.env"
  web:
    build: 
      context: .
      dockerfile: dockerfile.client  # Specify the name of the Dockerfile
    ports:
      - "${REACT_APP_WEB_PORT_HOST}:${REACT_APP_WEB_PORT_CONTAINER}" #3006 is the internal port hosted on inside the docker
    depends_on:
      - higlass
      - web_api
    volumes:
      - ${PWD}:${REACT_APP_CONTAINER_MOUNT_POINT}
    networks:
      - backend
    container_name: "web${REACT_APP_TEST}"
    env_file:
      - "${PWD}/.env"

volumes:
  web_data:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: ${PWD}
  db-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data/

  db-data-higlass-tmp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data/higlassTempData

  db-data-higlass-data:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: ${PWD}/data/higlassTracks

networks:
  backend: