services:
  higlass:
    image: "higlass/higlass-docker"
    ports:
      - "8889:80"
    volumes:
      - db-data-higlass-data:/data
      - db-data-higlass-tmp:/tmp
    networks:
      - backend
    restart: always
  web_api:
    build: 
      context: .
      dockerfile: dockerfile.server  # Specify the name of the Dockerfile
    ports:
      - "8086:8086" #8086 is the internal port hosted on inside the docker
    depends_on:
      - higlass
    volumes:
      - web_data:/storage/store/Robin_ComprehensiveLoopCaller/
    networks:
      - backend
    restart: always
  flask_api:
    build: 
      context: .
      dockerfile: dockerfile.server  # Specify the name of the Dockerfile
    ports:
      - "8087:8087" #8087 is the internal port hosted on inside the docker
    depends_on:
      - higlass
    volumes:
      - web_data:/storage/store/Robin_ComprehensiveLoopCaller/
    networks:
      - backend
    command: npm run start-flask-api
    restart: always
  web:
    build: 
      context: .
      dockerfile: dockerfile.client  # Specify the name of the Dockerfile
    ports:
      - "3006:3006" #3006 is the internal port hosted on inside the docker
    depends_on:
      - higlass
      - web_api
    volumes:
      - web_data:/storage/store/Robin_ComprehensiveLoopCaller/
    networks:
      - backend
    restart: always

volumes:
  web_data:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: /storage/store/Robin_ComprehensiveLoopCaller
  db-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /storage/store/Robin_ComprehensiveLoopCaller/data

  db-data-higlass-tmp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /storage/store/Robin_ComprehensiveLoopCaller/data/higlassTempData/

  db-data-higlass-data:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: /storage/store/Robin_ComprehensiveLoopCaller/data/higlassTracks/

networks:
  backend: