# Use an appropriate base image
FROM ubuntu:latest

# Install necessary dependencies
RUN apt-get update && \
    apt-get install -y software-properties-common && \
    apt-get install -y wget && \
    apt-get install -y software-properties-common dirmngr && \
    apt-get install -y libcurl4-openssl-dev 

# Add R repository and key
RUN wget -qO- https://cloud.r-project.org/bin/linux/ubuntu/marutter_pubkey.asc | tee -a /etc/apt/trusted.gpg.d/cran_ubuntu_key.asc

RUN add-apt-repository "deb https://cloud.r-project.org/bin/linux/ubuntu $(lsb_release -cs)-cran40/" 

# Install R
RUN apt-get update && \
    apt install r-base r-base-dev -y

# install R deps
RUN Rscript -e "install.packages('data.table')"
RUN Rscript -e "install.packages('dplyr')"
RUN Rscript -e "install.packages('optparse')"
RUN Rscript -e "install.packages('BiocManager')"
RUN Rscript -e "BiocManager::install('GenomicRanges')"
RUN Rscript -e "BiocManager::install('CAGEfightR')"
RUN Rscript -e "install.packages('venn')"
RUN Rscript -e "install.packages('VennDiagram')"


# Install curl and other necessary system dependencies
RUN apt-get update && apt-get install -y curl software-properties-common

#node 
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
    && apt-get install -y nodejs

# Verify Node.js installation
RUN node -v && npm -v

#install python
RUN apt-get install -y python
RUN apt-get install -y python3-pip

#install gwak and clodius
RUN apt-get install -y libssl-dev
RUN pip install clodius
RUN apt-get install -y gawk

ENV NODE_PATH $NVM_DIR/v$NODE_VERSION/lib/node_modules
ENV PATH      $NVM_DIR/v$NODE_VERSION/bin:$PATH

WORKDIR /app/
COPY ./package.json /app/package.json
RUN npm install

WORKDIR /storage/store/Robin_ComprehensiveLoopCaller
CMD [ "npm", "run", "start-api-worker" ]