# Use an appropriate base image
FROM ubuntu:latest

# Install necessary dependencies
RUN apt-get update && \
    apt-get install -y software-properties-common && \
    apt-get install -y wget && \
    apt-get install -y software-properties-common dirmngr && \
    apt-get install -y libcurl4-openssl-dev 

# Add R repository and key
RUN wget -qO- https://cloud.r-project.org/bin/linux/ubuntu/marutter_pubkey.asc | tee -a /etc/apt/trusted.gpg.d/cran_ubuntu_key.asc

RUN add-apt-repository "deb https://cloud.r-project.org/bin/linux/ubuntu $(lsb_release -cs)-cran40/" 

# Install R
RUN apt-get update && \
    apt install r-base r-base-dev -y

# Install Bed Tools
RUN apt-get install -y bedtools

# Install curl and other necessary system dependencies
RUN apt-get update && apt-get install -y curl software-properties-common

#node 
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
    && apt-get install -y nodejs

# Verify Node.js installation
RUN node -v && npm -v

#install python
RUN apt-get install -y python
RUN apt-get install -y python3-pip

#install gwak and clodius
RUN apt-get install -y libssl-dev
RUN pip install clodius
RUN apt-get install -y gawk

ENV NODE_PATH $NVM_DIR/v$NODE_VERSION/lib/node_modules
ENV PATH      $NVM_DIR/v$NODE_VERSION/bin:$PATH

WORKDIR /app/
COPY ./package.json /app/package.json
RUN npm install

#install python3
RUN apt-get install -y python3
# Install ipykernel if it's not already installed
RUN pip install ipykernel
# Install the Python 3 kernel
RUN python3 -m ipykernel install --user --name python3 --display-name "Python 3"
#install jyupter notebook converter
RUN pip install nbconvert

#install all libs for graphing
RUN pip install matplotlib

# install R deps
RUN R -e "install.packages('data.table')"
RUN R -e "install.packages('dplyr')"
RUN R -e "install.packages('optparse')"
RUN R -e "install.packages('BiocManager')"
RUN R -e "BiocManager::install('GenomicRanges')"
# RUN R -e "BiocManager::install('CAGEfightR')"
RUN R -e "install.packages('venn')"
RUN R -e "install.packages('VennDiagram')"
RUN Rscript -e "install.packages('BiocManager')"
RUN Rscript -e "BiocManager::install('GenomicRanges')"

#double check genomic ranges is installed
RUN R -e "library(GenomicRanges); print('GenomicRanges is available')"
RUN Rscript -e "library(GenomicRanges); print('GenomicRanges is available')"

#get flask installed
RUN pip install flask-cors
RUN pip install -U Flask
RUN pip install python-dotenv

WORKDIR /storage/store/Robin_ComprehensiveLoopCaller
CMD [ "npm", "run", "start-api-worker" ]